apiVersion: v1
kind: Service
metadata:
  name: laravel-app
spec:
  selector:
    app: laravel
  type: NodePort
  ports:
    - name: web
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: ssh
      port: 22
      targetPort: 22
      nodePort: 30222
